% PAGES List of pages for help window
%
% Format:
%   pageList - cell array (nx3)
%
%   1st column: Description as it should appear in the listbox
%
%   2nd column: filename of the file for the corresponding topic
%               (without extension, "html" is assumed)
%
%   3rd column: Lengthlier description (currently unused, might be empty)
%
% Important notes:
%
%   * The variable needs to be named "pageList".
%
%   * The sequence of the entries (rows) in the pageList cell array
%     determines the sequence of entries in the listbox.

% Copyright (c) 2014, Till Biskup
% 2014-08-08

pageList = {...
    'trEPR Toolbox','toolbox'; ...
    'Welcome','welcome'; ...
    'GUI in 2 minutes','shortintro'; ...
    'Why a GUI?','whygui'; ...
    'Key concepts','keyconcepts'; ...
    'Info file','infofile'; ...
    'New features','newfeatures'; ...
    'Wishlist','wishlist'; ...
    'Key bindings','keybindings'; ...
    'Known bugs','knownbugs'; ...
    'Report a bug','bugreport'; ...
    'Other resources','resources'; ...
    'Disclaimer','disclaimer'; ...
    'Privacy','privacy'; ...
    'License','license'; ...
    };
