function varargout = trEPRgui_bugreportwindow(varargin)
% TREPRGUI Brief description of GUI.
%          Comments displayed at the command line in response 
%          to the help command. 

% (Leave a blank line following the help.)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Construct the components
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Check whether we have been called with parameter and whether that has the
% right format
if nargin && isa(varargin{1},'MException')
    [status,report] = trEPRbugReportHelper(varargin{1});
    if status disp('Hm... Something went wrong generating the bug report...'); end
else
    disp('Obviously, we''re called with none or the wrong parameter...');
    return;
end

% Make GUI effectively a singleton
singleton = findobj('Tag','trepr_gui_bugreportwindow');
if (singleton)
    figure(singleton);
    return;
end

%  Construct the components
hMainFigure = figure('Tag','trepr_gui_bugreportwindow',...
    'Visible','off',...
    'Name','trEPR GUI : Bug Report Window',...
    'Units','Pixels',...
    'Position',[50,150,750,500],...
    'Resize','off',...
    'NumberTitle','off', ...
    'Color',[1 .8 .8],...
    'Menu','none','Toolbar','none');

defaultBackground = get(hMainFigure,'Color');
guiSize = get(hMainFigure,'Position');
guiSize = guiSize([3,4]);

uicontrol('Tag','bugreportwindow_headline',...
    'Style','text',...
    'Parent',hMainFigure,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',14,...
    'Units','Pixels',...
    'HorizontalAlignment','Left',...
    'Position',[20 guiSize(2)-50 guiSize(1)-40 30],...
    'FontWeight','bold',...
    'Enable','on',...
    'String','Bug report helper');

description = uicontrol('Tag','bugreportdescription_text',...
    'Style','text',...
    'Parent',hMainFigure,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'HorizontalAlignment','Left',...
    'Position',[20 guiSize(2)-260 guiSize(1)-40 200],...
    'Enable','on',...
    'String','');


% Create the report window
textdisplay = uicontrol('Tag','bugreport_edit',...
    'Style','edit',...
    'Parent',hMainFigure,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'HorizontalAlignment','Left',...
    'Position',[20 70 guiSize(1)-40 guiSize(2)-300],...
    'Enable','on',...
    'Max',2,'Min',0,...
    'FontName','FixedWidth',...
    'String','');

uicontrol('Tag','bugreportapologies_text',...
    'Style','text',...
    'Parent',hMainFigure,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',14,...
    'Units','Pixels',...
    'HorizontalAlignment','Left',...
    'Position',[20 20 guiSize(1)-40 25],...
    'FontWeight','bold',...
    'Enable','on',...
    'String','"Be seeing you..."');

uicontrol('Tag','bugreportwindow_refresh_pushbutton',...
    'Style','pushbutton',...
    'Parent',hMainFigure,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[guiSize(1)-160 20 70 30],...
    'String','Reload',...
    'TooltipString','Reload bug report display',...
    'Callback',{@button_Callback,'refresh'}...
    );

uicontrol('Tag','bugreportwindow_close_pushbutton',...
    'Style','pushbutton',...
    'Parent',hMainFigure,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[guiSize(1)-90 20 70 30],...
    'String','Close',...
    'TooltipString','Close bug report window',...
    'Callback',{@button_Callback,'close'}...
    );

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Initialization tasks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Store handles in guidata
guidata(hMainFigure,guihandles);

% Make the GUI visible.
set(hMainFigure,'Visible','on');

% Set description text
descriptionText{1} = [...
    'It looks like an error occurred. '...
    'At least, the toolbox has caught an exception. '...
    'Details can be found in the text display below.'...
    'If you see this window, that normally means that you can continue '...
    'and at least save your work.'
    ];
descriptionText{end+1} = ' ';
descriptionText{end+1} = [...
    'To make life a bit easier for both, you as a user '...
    'and me as programmer of the toolbox, all necessary information '...
    'has been collected in the text display below. '...
    'Please, be so kind and simply copy and paste this information '...
    'into an email to the author of the toolbox.'
    ];
descriptionText{end+1} = ' ';
descriptionText{end+1} = [...
    'If not otherwise known, the email address of the programmer '...
    'can be found in the "Help:About" window.'
    ];
descriptionText{end+1} = ' ';
descriptionText{end+1} = [...
    'Thank you very much for your cooperation and your patience. '...
    'I''ll try to fix the bug as soon as my time allows.'
    ];
set(description,'String',descriptionText);

% Set bugreport text
set(textdisplay,'String',report);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Callbacks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function button_Callback(varargin)
    if nargin == 3
        task = varargin{3};
    else
        return;
    end
    
    switch task
        case 'refresh'
            set(textdisplay,'String',report);
        case 'close'
            try
                delete(hMainFigure);
            catch
            end
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Utility functions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

end
