function varargout = trEPRgui_aboutwindow()

% Make GUI effectively a singleton
singleton = findobj('Tag','easteregg');
if (singleton)
    h = figure(singleton);
    return;
end

title = 'trEPR Toolbox: About';
message1 = {...
    'A MATLAB(TM) toolbox'...
    'for analysing transient EPR data'...
    ''...
    'GUI: v. 0.2.0'...
    'Toolbox: v. 0.2.3b'...
    ''...
    '(c) 2005-2011, Till Biskup'...
    '<till@till-biskup.de>'...
    ''...
    'For more information'...
    'check the corresponding web page:'...
    ''...
    'http://till-biskup.de/de/software/matlab/trepr/'...
    };
position = [200,250,350,300];

%  Construct the components
hMainFigure = figure('Tag','easteregg',...
    'Visible','off',...
    'Name',title,...
    'Units','Pixels',...
    'Position',position,...
    'Resize','off',...
    'NumberTitle','off', ...
    'Color',[.95 .95 .95],...
    'Menu','none','Toolbar','none',...
    'CloseRequestFcn',{@closeWindow});

defaultBackground = get(hMainFigure,'Color');
scrollPanelHeight = 5000;

hMainPanel = uipanel('Tag','main_panel',...
    'parent',hMainFigure,...
    'Title','',...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'BorderType','none',...
    'Visible','on',...
    'Units','pixels',...
    'Position',[0 position(4)-scrollPanelHeight position(3) 600]...
    );

hMsg1 = uicontrol('Tag','msgwindow_text',...
    'Style','text',...
    'Parent',hMainPanel,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'HorizontalAlignment','Center',...
    'Position',[20 scrollPanelHeight-50 position(3)-40 30],...
    'FontUnits','Pixels',...
    'FontSize',24,...
    'String','trEPR toolbox'...
    );

hMsg2 = uicontrol('Tag','msgwindow_info_text',...
    'Style','text',...
    'Parent',hMainPanel,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'HorizontalAlignment','Center',...
    'Position',[20 scrollPanelHeight-position(4) position(3)-40 position(4)-20-35],...
    'FontUnits','Pixels',...
    'FontSize',12,...
    'String',message1...
    );

hMsg3 = uicontrol('Tag','msgwindow_contributors_text',...
    'Style','text',...
    'Parent',hMainPanel,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'HorizontalAlignment','Center',...
    'Position',[20 180 position(3)-40 scrollPanelHeight-position(4)-200],...
    'FontUnits','Pixels',...
    'FontSize',12,...
    'String',''...
    );

hMsg4 = uicontrol('Tag','msgwindow_end_text',...
    'Style','text',...
    'Parent',hMainPanel,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'HorizontalAlignment','Center',...
    'Position',[20 140 position(3)-40 30],...
    'FontUnits','Pixels',...
    'FontSize',12,...
    'String','THE END.'...
    );

closeBtn = uicontrol('Tag','msgwindow_close_pushbutton',...
    'Style','pushbutton',...
    'Parent',hMainPanel,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[position(3)/2-30 scrollPanelHeight-280 60 30],...
    'String','Close',...
    'TooltipString','Close "about" window',...
    'Callback',{@closeWindow}...
    );

%    'Position',[position(3)/2-30 20 60 30],...


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Initialization tasks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Read text for welcome message from file and display it
[path,~,~] = fileparts(mfilename);
contributorsMessageFile = fullfile(path,'private','contributors.txt');
contributorsMessageText = textFileRead(contributorsMessageFile);
set(hMsg3,'String',contributorsMessageText);

% Make the GUI visible.
set(hMainFigure,'Visible','on');

% Set focus to "Close" button
uicontrol(closeBtn);

% Define timer for all the fun stuff
t1 = timer( ...
    'StartDelay', 8, ...
    'TasksToExecute', 1, ...
    'ExecutionMode', 'fixedRate');
t1.TimerFcn = @(x,y)startTimer2;
t1.StopFcn =  @(x,y)delete(t1);

t2 = timer( ...
    'StartDelay', 1, ...
    'TasksToExecute', 1, ...
    'ExecutionMode', 'fixedRate');
t2.TimerFcn = @(x,y)startScrollTimer;
t2.StopFcn =  @(x,y)delete(t2);

t3 = timer( ...
    'StartDelay', 2, ...
    'Period', 0.05, ...
    'TasksToExecute', scrollPanelHeight-position(4), ...
    'ExecutionMode', 'fixedRate');

t4 = timer( ...
    'StartDelay', 4, ...
    'Period', 4, ...
    'TasksToExecute', 7, ...
    'ExecutionMode', 'fixedRate');

t3.TimerFcn = @(x,y)scrollPanel;
t3.StopFcn =  @(x,y)start(t4);

t4.TimerFcn = {@(x,y)finalMessages};
t4.StartFcn = @(x,y)delete(t3);
t4.StopFcn =  @(x,y)closeWindow;

starttime = clock();
start(t1);

if nargout
    varargout{1} = hMainPanel;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Callbacks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    function closeWindow(~,~)
        if isvalid(t1)
            stop(t1);
            delete(t1);
        end
        if isvalid(t2)
            stop(t2);
            delete(t2);
        end
        if isvalid(t3)
            stop(t3);
            delete(t3);
        end
        if isvalid(t4)
            stop(t4);
            delete(t4);
        end
        try
            delete(hMainFigure);
        catch
        end
    end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Utility functions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    function startTimer2(~,~)
        set(closeBtn,'Position',[position(3)/2-30 20 60 30]);
        start(t2);
    end

    function startScrollTimer(~,~)
        uicontrol('Tag','msgwindow_acknowledgements_text',...
            'Style','text',...
            'Parent',hMainPanel,...
            'BackgroundColor',defaultBackground,...
            'Units','Pixels',...
            'HorizontalAlignment','Center',...
            'Position',[20 scrollPanelHeight-280 position(3)-40 30],...
            'FontUnits','Pixels',...
            'FontSize',12,...
            'FontWeight','bold',...
            'String','Acknowledgements...'...
            );
        start(t3);
    end

    function scrollPanel(~,~)
        panelPos = get(hMainPanel,'Position');
        panelPos(2) = panelPos(2)+1;
        set(hMainPanel,'Position',panelPos);
    end

    function finalMessages(~,~)
        
        finalMsg = uicontrol('Tag','msgwindow_final_text',...
            'Style','text',...
            'Parent',hMainPanel,...
            'BackgroundColor',defaultBackground,...
            'Units','Pixels',...
            'HorizontalAlignment','Center',...
            'Position',[20 80 position(3)-40 30],...
            'FontUnits','Pixels',...
            'FontSize',12,...
            'String','Still there?'...
            );
        
        switch t4.TasksExecuted
            case 2
                set(finalMsg,'String',...
                    'Honestly, this is the end...');
            case 3
                set(finalMsg,'String',...
                    'Last one turns out the lights...');
            case 4
                set(finalMsg,'String',...
                    sprintf('You''re wasting already %i seconds of your time with watching this end titles.',...
                    round(etime(clock,starttime))));
            case 5
                set(finalMsg,'String',...
                    'Booooring...');
            case 6
                set(hMainPanel,'BackgroundColor',[0 0 0]);
                set(findobj('Parent',hMainPanel,'-not','Style','Pushbutton'),...
                    'BackgroundColor',[0 0 0]);
                set(hMsg4,'ForegroundColor',[1 0 0],'FontSize',18);
        end

    end

end