function varargout = trEPRgui_infowindow()
% TREPRGUI_ACCWINDOW Brief description of GUI.
%          Comments displayed at the command line in response 
%          to the help command. 

% (Leave a blank line following the help.)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Construct the components
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Make GUI effectively a singleton
singleton = findobj('Tag','trepr_gui_infowindow');
if (singleton)
    figure(singleton);
    varargout{1} = singleton;
    return;
end

%  Construct the components
hMainFigure = figure('Tag','trepr_gui_infowindow',...
    'Visible','off',...
    'Name','trEPR GUI : Info Window',...
    'Units','Pixels',...
    'Position',[30,50,860,670],...
    'Resize','off',...
    'NumberTitle','off', ...
    'KeyPressFcn',@keypress_Callback,...
    'Menu','none','Toolbar','none');

defaultBackground = get(hMainFigure,'Color');
noneditableBackground = [0.92 0.92 0.92];
editableBackground = [1 1 1];
editableWarningBackground = [1 0.85 0.85];
guiSize = get(hMainFigure,'Position');
guiSize = guiSize([3,4]);
panel_size = 240;
mainPanelWidth = 260;
mainPanelHeight = guiSize(2)-70;

% Create main controls panels
mp = uipanel('Tag','main_controls_panel',...
    'parent',hMainFigure,...
    'Title','Main controls',...
    'FontUnit','Pixel','Fontsize',12,...
    'FontWeight','bold',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[guiSize(1)-mainPanelWidth-20 70 mainPanelWidth guiSize(2)-90]);

handle_mp1 = uipanel('Tag','main_panel_dataset_panel',...
    'Parent',mp,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 450 panel_size 100],...
    'Title','Select datasets'...
    );
uicontrol('Tag','main_panel_dataset_listbox',...
    'Style','listbox',...
    'Parent',handle_mp1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 10 panel_size-20 70],...
    'String','',...
    'Callback',{@dataset_listbox_Callback}...
    );
handle_mp2 = uipanel('Tag','main_panel_togglebuttons_panel',...
    'Parent',mp,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 350 panel_size 90],...
    'Title','Select category'...
    );
% Create button group, toggle buttons for switching btw. panels
hButtonGroup = uibuttongroup('Tag','mainButtonGroup',...
    'BackgroundColor',defaultBackground,...
    'Parent',handle_mp2,...
    'BorderType','none',...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position', [10 10 panel_size-20 60],...
    'Visible','on',...
    'SelectionChangeFcn',{@tbg_Callback});
tb1 = uicontrol('Tag','datasets_togglebutton',...
    'Style','Toggle',...
	'Parent', hButtonGroup, ...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'String','General',...
    'TooltipString','Decide which datasets to accumulate',...
    'pos',[0 30 (panel_size-20)/2 30],...
    'Enable','on'...
    );
tb2 = uicontrol('Tag','settings_togglebutton',...
    'Style','Toggle',...
	'Parent', hButtonGroup, ...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'String','Parameters',...
    'TooltipString','Set parameters for accumulation',...
    'pos',[(panel_size-20)/2 30 (panel_size-20)/2 30],...
    'Enable','on'...
    );
tb3 = uicontrol('Tag','results_togglebutton',...
    'Style','Toggle',...
	'Parent', hButtonGroup, ...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'String','Display',...
    'TooltipString','Show results of accumulation',...
    'pos',[0 0 (panel_size-20)/2 30],...
    'Enable','on'...
    );
tb4 = uicontrol('Tag','datasets_togglebutton',...
    'Style','Toggle',...
	'Parent', hButtonGroup, ...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'String','History',...
    'TooltipString','Decide which datasets to accumulate',...
    'pos',[(panel_size-20)/2 0 (panel_size-20)/2 30],...
    'Enable','on'...
    );
handle_mp3 = uipanel('Tag','main_panel_about_panel',...
    'Parent',mp,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 200 panel_size 140],...
    'Title','About the current panel'...
    );
uicontrol('Tag','main_panel_about_text',...
    'Style','text',...
    'parent',handle_mp3,...
    'FontUnit','Pixel','Fontsize',12,...
    'FontAngle','italic',...
    'HorizontalAlignment','Left',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','editable fields',...
    'Position',[10 10 panel_size-20 100]);

handle_mp4 = uipanel('Tag','main_panel_fieldtype_panel',...
    'Parent',mp,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 70 panel_size 120],...
    'Title','Colour codes of fields'...
    );
uipanel('Tag','main_panel_editablebg_panel',...
    'Parent',handle_mp4,...
    'BackgroundColor',editableBackground,...
    'BorderType','none',...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 70 20 20],...
    'Title',''...
    );
uicontrol('Tag','main_panel_editablebg_text',...
    'Style','text',...
    'parent',handle_mp4,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','editable fields',...
    'Position',[40 70 panel_size-50 20]);
uipanel('Tag','main_panel_editablebg_panel',...
    'Parent',handle_mp4,...
    'BackgroundColor',editableWarningBackground,...
    'BorderType','none',...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 40 20 20],...
    'Title',''...
    );
uicontrol('Tag','main_panel_editablebg_text',...
    'Style','text',...
    'parent',handle_mp4,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','editable, but be CAREFUL!',...
    'Position',[40 40 panel_size-50 20]);
uipanel('Tag','main_panel_noneditablebg_panel',...
    'Parent',handle_mp4,...
    'BackgroundColor',noneditableBackground,...
    'BorderType','none',...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 10 20 20],...
    'Title',''...
    );
uicontrol('Tag','main_panel_noneditablebg_text',...
    'Style','text',...
    'parent',handle_mp4,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','not editable fields',...
    'Position',[40 10 panel_size-50 20]);

uicontrol('Tag','help_pushbutton',...
    'Style','pushbutton',...
	'Parent', mp, ...
    'BackgroundColor',defaultBackground,...
    'ForegroundColor',[0 0 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'FontWeight','bold',...
    'String','?',...
    'TooltipString','Display help for how to operate the info GUI',...
    'pos',[panel_size-15 10 25 25],...
    'Enable','on',...
    'Callback',@trEPRgui_ACC_helpwindow...
    );


% Create (switchable and overlaying) main panels
p1 = uipanel('Tag','dataset_panel',...
    'parent',hMainFigure,...
    'Title','General information',...
    'FontUnit','Pixel','Fontsize',12,...
    'FontWeight','bold',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[20 20 guiSize(1)-mainPanelWidth-50 guiSize(2)-40]);

p2 = uipanel('Tag','dataset_panel',...
    'parent',hMainFigure,...
    'Title','Parameters of the measurement',...
    'FontUnit','Pixel','Fontsize',12,...
    'FontWeight','bold',...
    'BackgroundColor',defaultBackground,...
    'Visible','off',...
    'Units','pixels',...
    'Position',[20 20 guiSize(1)-mainPanelWidth-50 guiSize(2)-40]);

p3 = uipanel('Tag','dataset_panel',...
    'parent',hMainFigure,...
    'Title','Display settings',...
    'FontUnit','Pixel','Fontsize',12,...
    'FontWeight','bold',...
    'BackgroundColor',defaultBackground,...
    'Visible','off',...
    'Units','pixels',...
    'Position',[20 20 guiSize(1)-mainPanelWidth-50 guiSize(2)-40]);

p4 = uipanel('Tag','dataset_panel',...
    'parent',hMainFigure,...
    'Title','History',...
    'FontUnit','Pixel','Fontsize',12,...
    'FontWeight','bold',...
    'BackgroundColor',defaultBackground,...
    'Visible','off',...
    'Units','pixels',...
    'Position',[20 20 guiSize(1)-mainPanelWidth-50 guiSize(2)-40]);

% Controls for p1
p1p1 = uipanel('Tag','general_panel_filename_panel',...
    'parent',p1,...
    'Title','File',...
    'FontUnit','Pixel','Fontsize',12,...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[10 480 mainPanelWidth*2+10 120]);
uicontrol('Tag','general_panel_filepath_text',...
    'Style','text',...
    'parent',p1p1,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','Path ',...
    'Position',[10 70 60 20]);
uicontrol('Tag','general_panel_filepath_edit',...
    'Style','edit',...
    'parent',p1p1,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'BackgroundColor',noneditableBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String',['Some very long text with many many characters, '...
    'such as to show whether a very long, kpd-style pathname would '...
    'fit into this edit box and whether there appears a scrollbar...'],...
    'Position',[80 70 mainPanelWidth*2-80 25]);
uicontrol('Tag','general_panel_filename_text',...
    'Style','text',...
    'parent',p1p1,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','Name ',...
    'Position',[10 40 60 20]);
uicontrol('Tag','general_panel_filename_edit',...
    'Style','edit',...
    'parent',p1p1,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'BackgroundColor',noneditableBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','Filename',...
    'Position',[80 40 mainPanelWidth*2-80 25]);
uicontrol('Tag','general_panel_fileformat_text',...
    'Style','text',...
    'parent',p1p1,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','Format ',...
    'Position',[10 10 60 20]);
uicontrol('Tag','general_panel_fileformat_edit',...
    'Style','edit',...
    'parent',p1p1,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'BackgroundColor',noneditableBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','File format (not yet supported...)',...
    'Position',[80 10 mainPanelWidth*2-80 25]);

p1p2 = uipanel('Tag','general_panel_label_panel',...
    'parent',p1,...
    'Title','Dataset',...
    'FontUnit','Pixel','Fontsize',12,...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[10 410 mainPanelWidth*2+10 60]);
uicontrol('Tag','general_panel_label_text',...
    'Style','text',...
    'parent',p1p2,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','Label ',...
    'Position',[10 10 60 20]);
uicontrol('Tag','general_panel_label_edit',...
    'Style','edit',...
    'parent',p1p2,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'BackgroundColor',editableBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','',...
    'Position',[80 10 mainPanelWidth*2-80 25]);

p1p3 = uipanel('Tag','general_panel_header_panel',...
    'parent',p1,...
    'Title','Header',...
    'FontUnit','Pixel','Fontsize',12,...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[10 10 mainPanelWidth*2+10 390]);
uicontrol('Tag','general_panel_header_edit',...
    'Style','edit',...
    'parent',p1p3,...
    'FontUnit','Pixel','Fontsize',12,...
    'FontName','FixedWidth',...
    'HorizontalAlignment','Left',...
    'BackgroundColor',noneditableBackground,...
    'Max',2,'Min',0,...
    'Visible','on',...
    'Units','pixels',...
    'String',{'  1: Header with line numbers','  2: ','  3: '},...
    'Position',[10 10 mainPanelWidth*2-10 360]);


% Controls for p2
p2p1 = uipanel('Tag','dataset_panel',...
    'parent',p2,...
    'Title','General',...
    'FontUnit','Pixel','Fontsize',12,...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[10 mainPanelHeight-120 mainPanelWidth 120]);
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 70 90 20],...
    'String','No. of runs '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p1,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 70 mainPanelWidth-120 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 40 90 20],...
    'String','Temperature '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p1,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 40 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p1,...
    'BackgroundColor',noneditableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 40 (mainPanelWidth-120)/3 25],...
    'String','K',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 10 90 20],...
    'String','Operator '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p1,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'Units','Pixels',...
    'Position',[110 10 mainPanelWidth-120 25],...
    'String','N/A',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );

p2p2 = uipanel('Tag','dataset_panel',...
    'parent',p2,...
    'Title','Transient',...
    'FontUnit','Pixel','Fontsize',12,...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[10+mainPanelWidth+10 mainPanelHeight-120 mainPanelWidth 120]);
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 70 90 20],...
    'String','No. of points '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p2,...
    'BackgroundColor',editableWarningBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 70 mainPanelWidth-120 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 40 90 20],...
    'String','Trigger pos. '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p2,...
    'BackgroundColor',editableWarningBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 40 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p2,...
    'BackgroundColor',noneditableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 40 (mainPanelWidth-120)/3 25],...
    'String','pt',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 10 90 20],...
    'String','Length '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p2,...
    'BackgroundColor',editableWarningBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 10 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p2,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 10 (mainPanelWidth-120)/3 25],...
    'String','us',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );

p2p3 = uipanel('Tag','dataset_panel',...
    'parent',p2,...
    'Title','Recorder',...
    'FontUnit','Pixel','Fontsize',12,...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[10 mainPanelHeight-310 mainPanelWidth 180]);
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 130 90 20],...
    'String','Sensitivity '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p3,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 130 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p3,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 130 (mainPanelWidth-120)/3 25],...
    'String','mV',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 100 90 20],...
    'String','Averages '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p3,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 100 mainPanelWidth-120 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 70 90 20],...
    'String','Time base '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p3,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 70 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p3,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 70 (mainPanelWidth-120)/3 25],...
    'String','us',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 40 90 20],...
    'String','Bandwidth '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p3,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 40 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p3,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 40 (mainPanelWidth-120)/3 25],...
    'String','MHz',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 10 90 20],...
    'String','Model '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p3,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'Units','Pixels',...
    'Position',[110 10 mainPanelWidth-120 25],...
    'String','N/A',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );

p2p4 = uipanel('Tag','dataset_panel',...
    'parent',p2,...
    'Title','Field',...
    'FontUnit','Pixel','Fontsize',12,...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[10+mainPanelWidth+10 mainPanelHeight-310 mainPanelWidth 180]);
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p4,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 130 90 20],...
    'String','Start '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p4,...
    'BackgroundColor',editableWarningBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 130 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p4,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 130 (mainPanelWidth-120)/3 25],...
    'String','G',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p4,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 100 90 20],...
    'String','End '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p4,...
    'BackgroundColor',editableWarningBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 100 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p4,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 100 (mainPanelWidth-120)/3 25],...
    'String','G',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p4,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 70 90 20],...
    'String','Step '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p4,...
    'BackgroundColor',editableWarningBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 70 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p4,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 70 (mainPanelWidth-120)/3 25],...
    'String','G',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p4,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 40 90 20],...
    'String','Calibration '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p4,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 40 mainPanelWidth-120 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );

p2p5 = uipanel('Tag','dataset_panel',...
    'parent',p2,...
    'Title','Bridge',...
    'FontUnit','Pixel','Fontsize',12,...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[10 mainPanelHeight-500 mainPanelWidth 180]);
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p5,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 130 90 20],...
    'String','MW frequency '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p5,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 130 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p5,...
    'BackgroundColor',noneditableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 130 (mainPanelWidth-120)/3 25],...
    'String','GHz',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p5,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 100 90 20],...
    'String','Attenuation '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p5,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 100 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p5,...
    'BackgroundColor',noneditableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 100 (mainPanelWidth-120)/3 25],...
    'String','dB',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p5,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 70 90 20],...
    'String','Power '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p5,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 70 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p5,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 70 (mainPanelWidth-120)/3 25],...
    'String','mW',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p5,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 40 90 20],...
    'String','Calibration '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p5,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 40 mainPanelWidth-120 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p5,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 10 90 20],...
    'String','Model '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p5,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'Units','Pixels',...
    'Position',[110 10 mainPanelWidth-120 25],...
    'String','N/A',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );

p2p6 = uipanel('Tag','dataset_panel',...
    'parent',p2,...
    'Title','Laser',...
    'FontUnit','Pixel','Fontsize',12,...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[10+mainPanelWidth+10 mainPanelHeight-500 mainPanelWidth 180]);
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 130 90 20],...
    'String','Wavelength '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p6,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 130 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p6,...
    'BackgroundColor',noneditableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 130 (mainPanelWidth-120)/3 25],...
    'String','nm',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 100 90 20],...
    'String','Rep. rate '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p6,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 100 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p6,...
    'BackgroundColor',noneditableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 100 (mainPanelWidth-120)/3 25],...
    'String','Hz',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 70 90 20],...
    'String','Power '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p6,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110 70 (mainPanelWidth-120)/3*2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p6,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[110+(mainPanelWidth-120)/3*2 70 (mainPanelWidth-120)/3 25],...
    'String','mJ',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 40 90 20],...
    'String','Model '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p6,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'Units','Pixels',...
    'Position',[110 40 mainPanelWidth-120 25],...
    'String','N/A',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'Units','Pixels',...
    'Position',[10 10 90 20],...
    'String','OPO / Dye '...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p2p6,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'Units','Pixels',...
    'Position',[110 10 mainPanelWidth-120 25],...
    'String','N/A',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );


% Controls for p3
p3p1 = uipanel('Tag','display_panel_display_panel',...
    'Parent',p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'FontWeight','bold',...
    'Units','Pixels',...
    'Position',[10 10 mainPanelWidth 590],...
    'Title','Display'...
    );
p3p1p1 = uipanel('Tag','slider_panel_position_panel',...
    'Parent',p3p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 mainPanelHeight-140 mainPanelWidth-20 110],...
    'Title','Position'...
    );
uicontrol('Tag','slider_panel_position_index_text',...
    'Style','text',...
    'Parent',p3p1p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 60 (mainPanelWidth-90)/2 25],...
    'String','index'...
    );
uicontrol('Tag','slider_panel_position_unit_text',...
    'Style','text',...
    'Parent',p3p1p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 60 (mainPanelWidth-90)/2 25],...
    'String','unit'...
    );
uicontrol('Tag','slider_panel_position_x_text',...
    'Style','text',...
    'Parent',p3p1p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 40 35 20],...
    'String','x'...
    );
uicontrol('Tag','slider_panel_position_x_index_edit',...
    'Style','edit',...
    'Parent',p3p1p1,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 40 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@position_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_position_x_unit_edit',...
    'Style','edit',...
    'Parent',p3p1p1,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 40 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@position_edit_Callback,'xunit'}...
    );
uicontrol('Tag','slider_panel_position_y_text',...
    'Style','text',...
    'Parent',p3p1p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 10 35 20],...
    'String','y'...
    );
uicontrol('Tag','slider_panel_position_y_index_edit',...
    'Style','edit',...
    'Parent',p3p1p1,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 10 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@position_edit_Callback,'yindex'}...
    );
uicontrol('Tag','slider_panel_position_y_unit_edit',...
    'Style','edit',...
    'Parent',p3p1p1,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 10 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@position_edit_Callback,'yunit'}...
    );

p3p1p2 = uipanel('Tag','slider_panel_scaling_panel',...
    'Parent',p3p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 mainPanelHeight-290 mainPanelWidth-20 140],...
    'Title','Scaling'...
    );
uicontrol('Tag','slider_panel_scaling_index_text',...
    'Style','text',...
    'Parent',p3p1p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 90 (mainPanelWidth-90)/2 25],...
    'String','factor'...
    );
uicontrol('Tag','slider_panel_scaling_unit_text',...
    'Style','text',...
    'Parent',p3p1p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 90 (mainPanelWidth-90)/2 25],...
    'String','Delta in units',...
    'TooltipString','Difference to unscaled in units' ...
    );
uicontrol('Tag','slider_panel_scaling_x_text',...
    'Style','text',...
    'Parent',p3p1p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 70 35 20],...
    'String','x'...
    );
uicontrol('Tag','slider_panel_scaling_x_index_edit',...
    'Style','edit',...
    'Parent',p3p1p2,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 70 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_scaling_x_unit_edit',...
    'Style','edit',...
    'Parent',p3p1p2,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 70 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'xunit'}...
    );
uicontrol('Tag','slider_panel_scaling_y_text',...
    'Style','text',...
    'Parent',p3p1p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 40 35 20],...
    'String','y'...
    );
uicontrol('Tag','slider_panel_scaling_y_index_edit',...
    'Style','edit',...
    'Parent',p3p1p2,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 40 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'yindex'}...
    );
uicontrol('Tag','slider_panel_scaling_y_unit_edit',...
    'Style','edit',...
    'Parent',p3p1p2,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 40 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'yunit'}...
    );
uicontrol('Tag','slider_panel_scaling_z_text',...
    'Style','text',...
    'Parent',p3p1p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 10 35 20],...
    'String','z'...
    );
uicontrol('Tag','slider_panel_scaling_z_index_edit',...
    'Style','edit',...
    'Parent',p3p1p2,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 10 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'zindex'}...
    );
uicontrol('Tag','slider_panel_scaling_z_unit_edit',...
    'Style','edit',...
    'Parent',p3p1p2,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 10 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@scaling_edit_Callback,'zunit'}...
    );

p3p1p3 = uipanel('Tag','slider_panel_displacement_panel',...
    'Parent',p3p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 mainPanelHeight-440 mainPanelWidth-20 140],...
    'Title','Displacement'...
    );
uicontrol('Tag','slider_panel_displacement_index_text',...
    'Style','text',...
    'Parent',p3p1p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 90 (mainPanelWidth-90)/2 25],...
    'String','index'...
    );
uicontrol('Tag','slider_panel_displacement_unit_text',...
    'Style','text',...
    'Parent',p3p1p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 90 (mainPanelWidth-90)/2 25],...
    'String','unit'...
    );
uicontrol('Tag','slider_panel_displacement_x_text',...
    'Style','text',...
    'Parent',p3p1p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 70 35 20],...
    'String','x'...
    );
uicontrol('Tag','slider_panel_displacement_x_index_edit',...
    'Style','edit',...
    'Parent',p3p1p3,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 70 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@displacement_edit_Callback,'xindex'}...
    );
uicontrol('Tag','slider_panel_displacement_x_unit_edit',...
    'Style','edit',...
    'Parent',p3p1p3,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 70 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@displacement_edit_Callback,'xunit'}...
    );
uicontrol('Tag','slider_panel_displacement_y_text',...
    'Style','text',...
    'Parent',p3p1p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 40 35 20],...
    'String','y'...
    );
uicontrol('Tag','slider_panel_displacement_y_index_edit',...
    'Style','edit',...
    'Parent',p3p1p3,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 40 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@displacement_edit_Callback,'yindex'}...
    );
uicontrol('Tag','slider_panel_displacement_y_unit_edit',...
    'Style','edit',...
    'Parent',p3p1p3,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 40 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@displacement_edit_Callback,'yunit'}...
    );
uicontrol('Tag','slider_panel_displacement_z_text',...
    'Style','text',...
    'Parent',p3p1p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 10 35 20],...
    'String','z'...
    );
uicontrol('Tag','slider_panel_displacement_z_index_edit',...
    'Style','edit',...
    'Parent',p3p1p3,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 10 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@displacement_edit_Callback,'zindex'}...
    );
uicontrol('Tag','slider_panel_displacement_z_unit_edit',...
    'Style','edit',...
    'Parent',p3p1p3,...
    'BackgroundColor',editableBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 10 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@displacement_edit_Callback,'zunit'}...
    );

p3p1p4 = uipanel('Tag','processing_panel_average_panel',...
    'Parent',p3p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 mainPanelHeight-590 mainPanelWidth-20 140],...
    'Title','Smoothing (running average filter)'...
    );
uicontrol('Tag','processing_panel_average_type_text',...
    'Style','text',...
    'Parent',p3p1p4,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 90 35 20],...
    'String','type'...
    );
uicontrol('Tag','processing_panel_average_type_popupmenu',...
    'Style','popupmenu',...
    'Parent',p3p1p4,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[55 95 mainPanelWidth-80 20],...
    'String','simple_filter'...
    );
uicontrol('Tag','processing_panel_average_points_text',...
    'Style','text',...
    'Parent',p3p1p4,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 60 (mainPanelWidth-90)/2 25],...
    'String','points'...
    );
uicontrol('Tag','processing_panel_average_unit_text',...
    'Style','text',...
    'Parent',p3p1p4,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 60 (mainPanelWidth-90)/2 25],...
    'String','unit'...
    );
uicontrol('Tag','processing_panel_average_x_text',...
    'Style','text',...
    'Parent',p3p1p4,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 40 35 20],...
    'String','x'...
    );
uicontrol('Tag','processing_panel_average_x_points_edit',...
    'Style','edit',...
    'Parent',p3p1p4,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 40 (mainPanelWidth-90)/2 25],...
    'String','1',...
    'Callback',{@average_x_points_Callback}...
    );
uicontrol('Tag','processing_panel_average_x_unit_edit',...
    'Style','edit',...
    'Parent',p3p1p4,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 40 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@average_x_unit_Callback}...
    );
uicontrol('Tag','processing_panel_average_y_text',...
    'Style','text',...
    'Parent',p3p1p4,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 10 35 20],...
    'String','y'...
    );
uicontrol('Tag','processing_panel_average_y_points_edit',...
    'Style','edit',...
    'Parent',p3p1p4,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 10 (mainPanelWidth-90)/2 25],...
    'String','1',...
    'Callback',{@average_y_points_Callback}...
    );
uicontrol('Tag','processing_panel_average_y_unit_edit',...
    'Style','edit',...
    'Parent',p3p1p4,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 10 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@average_y_unit_Callback}...
    );

p3p2 = uipanel('Tag','display_panel_axis_panel',...
    'Parent',p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'FontWeight','bold',...
    'Units','Pixels',...
    'Position',[mainPanelWidth+20 280 mainPanelWidth 320],...
    'Title','Axes'...
    );
p3p2p6 = uipanel('Tag','display_panel_axislabels_panel',...
    'Parent',p3p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 160 mainPanelWidth-20 140],...
    'Title','Axis labels'...
    );
uicontrol('Tag','display_panel_axislabels_measure_text',...
    'Style','text',...
    'Parent',p3p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 90 (mainPanelWidth-90)/2 25],...
    'String','Measure'...
    );
uicontrol('Tag','display_panel_axislabels_unit_text',...
    'Style','text',...
    'Parent',p3p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 90 (mainPanelWidth-90)/2 25],...
    'String','Unit'...
    );
uicontrol('Tag','display_panel_axislabels_x_text',...
    'Style','text',...
    'Parent',p3p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 70 35 20],...
    'String','x'...
    );
uicontrol('Tag','display_panel_axislabels_x_measure_edit',...
    'Style','edit',...
    'Parent',p3p2p6,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 70 (mainPanelWidth-90)/2 25],...
    'String','index',...
    'Callback',{@axislabels_edit_Callback,'xmeasure'}...
    );
uicontrol('Tag','display_panel_axislabels_x_unit_edit',...
    'Style','edit',...
    'Parent',p3p2p6,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 70 (mainPanelWidth-90)/2 25],...
    'String','points',...
    'Callback',{@axislabels_edit_Callback,'xunit'}...
    );
uicontrol('Tag','display_panel_axislabels_y_text',...
    'Style','text',...
    'Parent',p3p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 40 35 20],...
    'String','y'...
    );
uicontrol('Tag','display_panel_axislabels_y_measure_edit',...
    'Style','edit',...
    'Parent',p3p2p6,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 40 (mainPanelWidth-90)/2 25],...
    'String','index',...
    'Callback',{@axislabels_edit_Callback,'ymeasure'}...
    );
uicontrol('Tag','display_panel_axislabels_y_unit_edit',...
    'Style','edit',...
    'Parent',p3p2p6,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 40 (mainPanelWidth-90)/2 25],...
    'String','points',...
    'Callback',{@axislabels_edit_Callback,'yunit'}...
    );
uicontrol('Tag','display_panel_axislabels_z_text',...
    'Style','text',...
    'Parent',p3p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 10 35 20],...
    'String','z'...
    );
uicontrol('Tag','display_panel_axislabels_z_measure_edit',...
    'Style','edit',...
    'Parent',p3p2p6,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 10 (mainPanelWidth-90)/2 25],...
    'String','index',...
    'Callback',{@axislabels_edit_Callback,'zmeasure'}...
    );
uicontrol('Tag','display_panel_axislabels_z_unit_edit',...
    'Style','edit',...
    'Parent',p3p2p6,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 10 (mainPanelWidth-90)/2 25],...
    'String','points',...
    'Callback',{@axislabels_edit_Callback,'zunit'}...
    );

p3p2p6 = uipanel('Tag','display_panel_axislimits_panel',...
    'Parent',p3p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 10 mainPanelWidth-20 140],...
    'Title','Axis limits'...
    );
uicontrol('Tag','display_panel_axislimits_min_text',...
    'Style','text',...
    'Parent',p3p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 90 (mainPanelWidth-90)/2 25],...
    'String','min'...
    );
uicontrol('Tag','display_panel_axislimits_max_text',...
    'Style','text',...
    'Parent',p3p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 90 (mainPanelWidth-90)/2 25],...
    'String','max'...
    );
uicontrol('Tag','display_panel_axislimits_x_text',...
    'Style','text',...
    'Parent',p3p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 70 35 20],...
    'String','x'...
    );
uicontrol('Tag','display_panel_axislimits_x_min_edit',...
    'Style','edit',...
    'Parent',p3p2p6,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 70 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@axislimits_edit_Callback,'xmin'}...
    );
uicontrol('Tag','display_panel_axislimits_x_max_edit',...
    'Style','edit',...
    'Parent',p3p2p6,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 70 (mainPanelWidth-90)/2 25],...
    'String','1',...
    'Callback',{@axislimits_edit_Callback,'xmax'}...
    );
uicontrol('Tag','display_panel_axislimits_y_text',...
    'Style','text',...
    'Parent',p3p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 40 35 20],...
    'String','y'...
    );
uicontrol('Tag','display_panel_axislimits_y_min_edit',...
    'Style','edit',...
    'Parent',p3p2p6,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 40 (mainPanelWidth-90)/2 25],...
    'String','0',...
    'Callback',{@axislimits_edit_Callback,'ymin'}...
    );
uicontrol('Tag','display_panel_axislimits_y_max_edit',...
    'Style','edit',...
    'Parent',p3p2p6,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 40 (mainPanelWidth-90)/2 25],...
    'String','1',...
    'Callback',{@axislimits_edit_Callback,'ymax'}...
    );
uicontrol('Tag','display_panel_axislimits_z_text',...
    'Style','text',...
    'Parent',p3p2p6,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 10 35 20],...
    'String','z'...
    );
uicontrol('Tag','display_panel_axislimits_z_min_edit',...
    'Style','edit',...
    'Parent',p3p2p6,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60 10 (mainPanelWidth-90)/2 25],...
    'String','-1',...
    'Callback',{@axislimits_edit_Callback,'zmin'}...
    );
uicontrol('Tag','display_panel_axislimits_z_max_edit',...
    'Style','edit',...
    'Parent',p3p2p6,...
    'BackgroundColor',[1 1 1],...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[60+(mainPanelWidth-90)/2 10 (mainPanelWidth-90)/2 25],...
    'String','1',...
    'Callback',{@axislimits_edit_Callback,'zmax'}...
    );


p3p3 = uipanel('Tag','display_panel_linestyle_panel',...
    'Parent',p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'FontWeight','bold',...
    'Units','Pixels',...
    'Position',[mainPanelWidth+20 10 mainPanelWidth 260],...
    'Title','Line'...
    );
p3p3p1 = uipanel('Tag','display_panel_highlight_panel',...
    'Parent',p3p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 140 mainPanelWidth-20 100],...
    'Title','Color'...
    );
uicontrol('Tag','display_panel_highlight_method_text',...
    'Style','text',...
    'Parent',p3p3p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 10 60 20],...
    'String','Color'...
    );
uicontrol('Tag','display_panel_highlight_method_popupmenu',...
    'Style','popupmenu',...
    'Parent',p3p3p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[80 10 mainPanelWidth-105 20],...
    'String','color|linewidth|linestyle|marker',...
    'Callback',{@highlight_method_popupmenu_Callback}...
    );

p3p3p2 = uipanel('Tag','display_panel_highlight_panel',...
    'Parent',p3p3,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 10 mainPanelWidth-20 120],...
    'Title','Line settings'...
    );
uicontrol('Tag','display_panel_highlight_method_text',...
    'Style','text',...
    'Parent',p3p3p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 70 60 20],...
    'String','Width'...
    );
uicontrol('Tag','display_panel_highlight_method_popupmenu',...
    'Style','popupmenu',...
    'Parent',p3p3p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[80 70 mainPanelWidth-105 20],...
    'String','1 px|2 px|3 px|4 px|5 px',...
    'Callback',{@highlight_method_popupmenu_Callback}...
    );
uicontrol('Tag','display_panel_highlight_method_text',...
    'Style','text',...
    'Parent',p3p3p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 40 60 20],...
    'String','Style'...
    );
uicontrol('Tag','display_panel_highlight_method_popupmenu',...
    'Style','popupmenu',...
    'Parent',p3p3p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[80 40 mainPanelWidth-105 20],...
    'String','solid|dashed|dotted|dash-dotted',...
    'Callback',{@highlight_method_popupmenu_Callback}...
    );
uicontrol('Tag','display_panel_highlight_value_text',...
    'Style','text',...
    'Parent',p3p3p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 10 60 20],...
    'String','Marker'...
    );
uicontrol('Tag','display_panel_highlight_value_popupmenu',...
    'Style','popupmenu',...
    'Parent',p3p3p2,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[80 10 mainPanelWidth-105 20],...
    'String',['plus|circle|asterisk|point|cross|square|diamond|'...
    'triangle up|triangle down|triangle right|triangle left|'...
    'pentagram|hexagram'],...
    'Callback',{@highlight_value_popupmenu_Callback}...
    );


% Controls for p4
p4p1 = uipanel('Tag','history_panel_records_panel',...
    'parent',p4,...
    'Title','History record',...
    'FontUnit','Pixel','Fontsize',12,...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[10 500 mainPanelWidth 100]);
uicontrol('Tag','history_panel_records_listbox',...
    'Style','listbox',...
    'Parent',p4p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 10 panel_size 70],...
    'String',''...
    );

p4p2 = uipanel('Tag','history_panel_summary_panel',...
    'parent',p4,...
    'Title','Summary',...
    'FontUnit','Pixel','Fontsize',12,...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[10+mainPanelWidth+10 500 mainPanelWidth 100]);
uicontrol('Tag','history_panel_datelabel_text',...
    'Style','text',...
    'parent',p4p2,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','Date: ',...
    'Position',[10 50 70 20]);
uicontrol('Tag','history_panel_date_text',...
    'Style','text',...
    'parent',p4p2,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','xxxx-xx-xx ##:##:##',...
    'Position',[85 50 panel_size-75 20]);
uicontrol('Tag','history_panel_methodlabel_text',...
    'Style','text',...
    'parent',p4p2,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','Method: ',...
    'Position',[10 30 70 20]);
uicontrol('Tag','history_panel_method_text',...
    'Style','text',...
    'parent',p4p2,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','Some method name',...
    'Position',[85 30 panel_size-75 20]);
uicontrol('Tag','history_panel_operatorlabel_text',...
    'Style','text',...
    'parent',p4p2,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Right',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','Operator: ',...
    'Position',[10 10 70 20]);
uicontrol('Tag','history_panel_operator_text',...
    'Style','text',...
    'parent',p4p2,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','Left',...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'String','Some operator name',...
    'Position',[85 10 panel_size-75 20]);

p4p3 = uipanel('Tag','history_panel_parameter_panel',...
    'parent',p4,...
    'Title','Parameters',...
    'FontUnit','Pixel','Fontsize',12,...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[10 260 mainPanelWidth*2+10 230]);
uicontrol('Tag','history_panel_parameter_edit',...
    'Style','edit',...
    'parent',p4p3,...
    'FontUnit','Pixel','Fontsize',12,...
    'FontName','FixedWidth',...
    'HorizontalAlignment','Left',...
    'BackgroundColor',noneditableBackground,...
    'Max',2,'Min',0,...
    'Visible','on',...
    'Units','pixels',...
    'String','No parameters to display currently',...
    'Position',[10 10 mainPanelWidth*2-10 200]);

p4p4 = uipanel('Tag','history_panel_report_panel',...
    'parent',p4,...
    'Title','Report',...
    'FontUnit','Pixel','Fontsize',12,...
    'BackgroundColor',defaultBackground,...
    'Visible','on',...
    'Units','pixels',...
    'Position',[10 10 mainPanelWidth*2+10 240]);
uicontrol('Tag','history_panel_report_edit',...
    'Style','edit',...
    'parent',p4p4,...
    'FontUnit','Pixel','Fontsize',12,...
    'FontName','FixedWidth',...
    'HorizontalAlignment','Left',...
    'BackgroundColor',noneditableBackground,...
    'Max',2,'Min',0,...
    'Visible','on',...
    'Units','pixels',...
    'String','No information to display currently',...
    'Position',[10 10 mainPanelWidth*2-10 210]);


%--------------------------------------------
% Create controls for main buttons bottom left
uicontrol('Tag','apply_pushbutton',...
    'Style','pushbutton',...
	'Parent', hMainFigure, ...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'String','Apply',...
    'TooltipString','Apply current settings',...
    'pos',[guiSize(1)-mainPanelWidth-20 20 (mainPanelWidth)/3 40],...
    'Enable','on',...
    'Callback',{@pushbutton_Callback,'Apply'}...
    );
uicontrol('Tag','discard_pushbutton',...
    'Style','pushbutton',...
	'Parent', hMainFigure, ...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'String','Discard',...
    'TooltipString','Discard changes (revert to original settings)',...
    'pos',[guiSize(1)-((mainPanelWidth)/3*2)-20 20 (mainPanelWidth)/3 40],...
    'Enable','on',...
    'Callback',{@pushbutton_Callback,'Discard'}...
    );
uicontrol('Tag','close_pushbutton',...
    'Style','pushbutton',...
	'Parent', hMainFigure, ...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'String','Close',...
    'TooltipString','Close Info Window',...
    'pos',[guiSize(1)-((mainPanelWidth)/3)-20 20 (mainPanelWidth)/3 40],...
    'Enable','on',...
    'Callback',{@pushbutton_Callback,'Close'}...
    );


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Initialization tasks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Store handles in guidata
guidata(hMainFigure,guihandles);

% Create appdata structure
ad = struct();
% data - empty cell array
ad.data = cell(0);
% origdata - empty cell array
ad.origdata = cell(0);
% configuration - struct
ad.configuration = struct();
% control - struct
ad.control = struct();
% control.spectra - struct
ad.control.spectra = struct();
ad.control.spectra.active = 0;
ad.control.spectra.loaded = [];
ad.control.spectra.modified = [];

setappdata(hMainFigure,'data',ad.data);
setappdata(hMainFigure,'origdata',ad.origdata);
setappdata(hMainFigure,'configuration',ad.configuration);
setappdata(hMainFigure,'control',ad.control);

% Set everything for first panel
switchPanel('General');

% Load data from Main GUI
mainGuiWindow = guiGetWindowHandle();
if (mainGuiWindow)
    admain = getappdata(mainGuiWindow);
    % Check for availability of necessary fields in appdata
    if (isfield(admain,'data') ~= 0)
        ad.data = admain.data;
        setappdata(hMainFigure,'data',ad.data);
        ad.origdata = admain.data;
        setappdata(hMainFigure,'origdata',ad.origdata);
    end
    if (isfield(admain,'control') ~= 0)
        ad.control = admain.control;
        % Move (in)visible -> loaded
        ad.control.spectra.loaded = [ ...
            admain.control.spectra.visible ...
        	admain.control.spectra.invisible ...
            ];
        ad.control.spectra = rmfield(ad.control.spectra,'visible');
        ad.control.spectra = rmfield(ad.control.spectra,'invisible');
        setappdata(hMainFigure,'control',ad.control);
    end
    
    updateDatasets();
    updateGeneralPanel();
%    updateDimensionPanel('Datasets');
%     update_position_display();
end

% Make the GUI visible.
set(hMainFigure,'Visible','on');

if (nargout == 1)
    varargout{1} = hMainFigure;
end

% Add keypress function to every element that can have one...
handles = findall(...
    allchild(hMainFigure),'style','pushbutton',...
    '-or','style','togglebutton',...
    '-or','style','edit',...
    '-or','style','listbox',...
    '-or','style','popupmenu');
for k=1:length(handles)
    set(handles(k),'KeyPressFcn',@keypress_Callback);
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Callbacks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


function tbg_Callback(source,~)
    try 
        switchPanel(get(get(source,'SelectedObject'),'String'));
    catch exception
        try
            msgStr = ['An exception occurred. '...
                'The bug reporter should have been opened'];
            add2status(msgStr);
        catch exception2
            exception = addCause(exception2, exception);
            disp(msgStr);
        end
        try
            trEPRgui_bugreportwindow(exception);
        catch exception3
            % If even displaying the bug report window fails...
            exception = addCause(exception3, exception);
            throw(exception);
        end
    end
end

function dataset_listbox_Callback(source,~)
    try
        % Get appdata of main window
        mainWindow = guiGetWindowHandle('trEPRgui_infowindow');
        ad = getappdata(mainWindow);
        
        ad.control.spectra.active = ad.control.spectra.loaded(...
            get(source,'Value')...
            );
        
        % Update appdata of main window
        setappdata(mainWindow,'control',ad.control);
        
        % Update panels
        updateGeneralPanel();
    catch exception
        try
            msgStr = ['An exception occurred. '...
                'The bug reporter should have been opened'];
            add2status(msgStr);
        catch exception2
            exception = addCause(exception2, exception);
            disp(msgStr);
        end
        try
            trEPRgui_bugreportwindow(exception);
        catch exception3
            % If even displaying the bug report window fails...
            exception = addCause(exception3, exception);
            throw(exception);
        end
    end
end

function pushbutton_Callback(~,~,action)
    try
        if isempty(action)
            return;
        end
        
        switch action
            case 'Close'
                % Look for ACC GUI Help window and if its there, close as
                % well
%                 hHelpWindow = findobj('Tag','trEPRgui_ACC_helpwindow');
%                 if ishandle(hHelpWindow)
%                     delete(hHelpWindow);
%                 end
                delete(findobj('Tag','trepr_gui_infowindow'));
            otherwise
                return;
        end
    catch exception
        try
            msgStr = ['An exception occurred. '...
                'The bug reporter should have been opened'];
            add2status(msgStr);
        catch exception2
            exception = addCause(exception2, exception);
            disp(msgStr);
        end
        try
            trEPRgui_bugreportwindow(exception);
        catch exception3
            % If even displaying the bug report window fails...
            exception = addCause(exception3, exception);
            throw(exception);
        end
    end
end

function keypress_Callback(src,evt)
    try
        if isempty(evt.Character) && isempty(evt.Key)
            % In case "Character" is the empty string, i.e. only modifier key
            % was pressed...
            return;
        end
        if ~isempty(evt.Modifier)
            if (strcmpi(evt.Modifier{1},'command')) || ...
                    (strcmpi(evt.Modifier{1},'control'))
                switch evt.Key
                    case 'w'
                        pushbutton_Callback(src,evt,'Close')
                        return;
                    case '1'
                        switchPanel('General');
                        return;
                    case '2'
                        switchPanel('Parameters');
                        return;
                    case '3'
                        switchPanel('Display');
                        return;
                    case '4'
                        switchPanel('History');
                        return;
                end
            end
        end
        switch evt.Key
            case 'f1'
                trEPRgui_ACC_helpwindow();
                return;
            otherwise
%                 disp(evt);
%                 fprintf('       Caller: %i\n\n',src);
                return;
        end
    catch exception
        try
            msgStr = ['An exception occurred. '...
                'The bug reporter should have been opened'];
            add2status(msgStr);
        catch exception2
            exception = addCause(exception2, exception);
            disp(msgStr);
        end
        try
            trEPRgui_bugreportwindow(exception);
        catch exception3
            % If even displaying the bug report window fails...
            exception = addCause(exception3, exception);
            throw(exception);
        end
    end
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Utility functions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function switchPanel(panelName)
    try
        % Get handles of main window
        mainWindow = guiGetWindowHandle(mfilename);
        gh = guihandles(mainWindow);

        panels = [p1 p2 p3 p4];
        buttons = [tb1 tb2 tb3 tb4];
        switch panelName
            case 'General'
                set(panels,'Visible','off');
                set(buttons,'Value',0);
                set(p1,'Visible','on');
                set(tb1,'Value',1);
                set(gh.main_panel_about_text,'String',...
                    ['General information about the dataset, such as '...
                    'full filename (with path), label, and header '...
                    'information. In case of Bruker BES3T files, '...
                    '"header" displays the content of the DSC file.']);
            case 'Parameters'
                set(panels,'Visible','off');
                set(buttons,'Value',0);
                set(p2,'Visible','on');
                set(tb2,'Value',1);
                set(gh.main_panel_about_text,'String',{...
                    ['All information from the "parameters" structure '...
                    'of the dataset. Most of these parameters are '...
                    'extracted from the raw data. ']...
                    ['Be careful with editing the highlighted '...
                    'fields, as that may corrupt your data!']...
                    });
            case 'Display'
                set(panels,'Visible','off');
                set(buttons,'Value',0);
                set(p3,'Visible','on');
                set(tb3,'Value',1);
                set(gh.main_panel_about_text,'String',...
                    ['All settings that control the display of the '...
                    'dataset, including position in x and y, '...
                    'scaling, displacement, smoothing, axis labels '...
                    'and limits, but as well the line style.']);
            case 'History'
                set(panels,'Visible','off');
                set(buttons,'Value',0);
                set(p4,'Visible','on');
                set(tb4,'Value',1);
                set(gh.main_panel_about_text,'String',{...
                    ['Access to the complete history of the dataset '...
                    'including a detailed account of the parameters '...
                    'used for every step in the history. ']...
                    ['If there is a report from a given record, '...
                    'it will be displayed as well.']...
                    });
            otherwise
                return;
        end
    catch exception
        try
            msgStr = ['An exception occurred. '...
                'The bug reporter should have been opened'];
            add2status(msgStr);
        catch exception2
            exception = addCause(exception2, exception);
            disp(msgStr);
        end
        try
            trEPRgui_bugreportwindow(exception);
        catch exception3
            % If even displaying the bug report window fails...
            exception = addCause(exception3, exception);
            throw(exception);
        end
    end 
end

function updateDatasets()
    try
        mainWindow = findobj('Tag','trepr_gui_infowindow');
        % Get appdata from ACC GUI
        ad = getappdata(mainWindow);
        
        if isempty(ad.data)
            return;
        end
        
        % Get handle for loaded spectra listbox
        gh = guidata(mainWindow);
        lbox = gh.main_panel_dataset_listbox;
        
        % Get indices of loaded spectra
        loaded = ad.control.spectra.loaded;
        
        % Get names for display in listbox
        if length(loaded)>0
            set(lbox,'Enable','on');
            labels = cell(0);
            for k=1:length(loaded)
                labels{k} = ad.data{loaded(k)}.label;
            end
            % Update status display
            set(lbox,'String',labels);
            if (get(lbox,'Value')>length(loaded))
                set(lbox,'Value',length(loaded));
            end
            if ((get(lbox,'Value')==0) && (length(loaded)>0))
                set(lbox,'Value',1);
            end
            ad.control.spectra.active = loaded(get(lbox,'Value'));
        else
            set(lbox,'String','');
            set(lbox,'Enable','off');
            ad.control.spectra.active = [];
        end
        
        % Highlight currently active
        if ad.control.spectra.active
            set(lbox,'Value',find(loaded==ad.control.spectra.active));
        end
        
        % Set appdata of info GUI
        setappdata(mainWindow,'control',ad.control);

    catch exception
        try
            msgStr = ['An exception occurred. '...
                'The bug reporter should have been opened'];
            add2status(msgStr);
        catch exception2
            exception = addCause(exception2, exception);
            disp(msgStr);
        end
        try
            trEPRgui_bugreportwindow(exception);
        catch exception3
            % If even displaying the bug report window fails...
            exception = addCause(exception3, exception);
            throw(exception);
        end
    end 
end


function updateGeneralPanel()
    try
        mainWindow = findobj('Tag','trepr_gui_infowindow');
        % Get appdata from info GUI
        ad = getappdata(mainWindow);
        
        if isempty(ad.data)
            return;
        end
        
        % Get handles from info GUI
        gh = guidata(mainWindow);
        
        [filepath,filename,fileext] = ...
            fileparts(ad.data{ad.control.spectra.active}.filename);
        if filepath
            filepath = [filepath '/'];
        end
        set(gh.general_panel_filepath_edit,'String',filepath);
        set(gh.general_panel_filename_edit,'String',[filename fileext]);
        set(gh.general_panel_label_edit,'String',...
            ad.data{ad.control.spectra.active}.label);
        
        for k=1:length(ad.data{ad.control.spectra.active}.header)
            ad.data{ad.control.spectra.active}.header{k} = ...
                sprintf('%03.0f: %s',...
                k,char(ad.data{ad.control.spectra.active}.header{k}));
        end
        set(gh.general_panel_header_edit,'String',...
            ad.data{ad.control.spectra.active}.header);

    catch exception
        try
            msgStr = ['An exception occurred. '...
                'The bug reporter should have been opened'];
            add2status(msgStr);
        catch exception2
            exception = addCause(exception2, exception);
            disp(msgStr);
        end
        try
            trEPRgui_bugreportwindow(exception);
        catch exception3
            % If even displaying the bug report window fails...
            exception = addCause(exception3, exception);
            throw(exception);
        end
    end 
end

end