function varargout = trEPRgui_setLabelWindow(varargin)
% TREPRGUI_SETLABELWINDOW Set label of dataset that is used for display in
% the dataset lists.
%
% Usage
%   label = trEPRgui_setLabelWindow;
%   label = trEPRgui_setLabelWindow(oldlabel);
%   [label,status] = trEPRgui_setLabelWindow;
%   [label,status] = trEPRgui_setLabelWindow(oldlabel);
%
% Output
%   status    - return value of the function. Either 0 (OK) or -1 (failed)

% (c) 2011-13, Till Biskup, Bernd Paulus
% 2013-02-04

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Construct the components
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

title = 'Set label of dataset';
description = {...
    'Set the label of the selected dataset.' ...
    ' ' ...
    'TIP: Use short, precise and easily recognizable labels.' ...
    };
position = [200,300,300,160];

if (nargin > 0)
    oldLabel = varargin{1};
else
    oldLabel = '';
end

%  Construct the components
hMainFigure = figure('Tag',mfilename,...
    'Visible','off',...
    'Name',title,...
    'Units','Pixels',...
    'Position',position,...
    'Resize','off',...
    'NumberTitle','off', ...
    'WindowStyle','modal',...
    'Menu','none','Toolbar','none',...
    'KeyPressFcn',@keypress_Callback,...
    'CloseRequestFcn',{@setLabel_Callback,'cancel'});

defaultBackground = get(hMainFigure,'Color');
guiSize = get(hMainFigure,'Position');
guiSize = guiSize([3,4]);

uicontrol('Tag','description',...
    'Style','text',...
    'Parent',hMainFigure,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'HorizontalAlignment','Left',...
    'Position',[10 85 guiSize(1)-20 65],...
    'String',description...
    );

edit = uicontrol('Tag','label_edit',...
    'Style','edit',...
    'Parent',hMainFigure,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 50 guiSize(1)-20 25],...
    'HorizontalAlignment','Left',...
    'String',oldLabel,...
    'Callback',{@setLabel_Callback,'apply'}...
    );

uicontrol('Tag','info_pushbutton',...
    'Style','pushbutton',...
    'Parent',hMainFigure,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 10 60 30],...
    'String','Get Info',...
    'TooltipString','Display more informations about selected dataset',...
    'Callback',{@info_pushbutton_Callback}...
    );

uicontrol('Tag','cancel_pushbutton',...
    'Style','pushbutton',...
    'Parent',hMainFigure,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[guiSize(1)-130 10 60 30],...
    'String','Cancel',...
    'TooltipString','Cancel and don''t change label text',...
    'Callback',{@setLabel_Callback,'cancel'}...
    );

uicontrol('Tag','apply_pushbutton',...
    'Style','pushbutton',...
    'Parent',hMainFigure,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[guiSize(1)-70 10 60 30],...
    'String','Apply',...
    'TooltipString','Return to GUI and use label text as shown',...
    'Callback',{@setLabel_Callback,'apply'}...
    );



% Create the message window

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Initialization tasks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Store handles in guidata
guidata(hMainFigure,guihandles);

% Make the GUI visible.
set(hMainFigure,'Visible','on');
trEPRmsg('Set label window opened.','info');

% Give edit control the focus
uicontrol(edit);

uiwait;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Callbacks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function setLabel_Callback(~,~,action)
    newLabel = get(edit,'String');
    switch action
        case 'apply'
            delete(hMainFigure);
            varargout{1} = newLabel;
            varargout{2} = 0;
        case 'cancel'
            delete(hMainFigure);
            trEPRmsg('Set label window closed.','info');
            varargout{1} = oldLabel;
            varargout{2} = -1;
        otherwise
            trEPRmsg([mfilename ...
                ': Whatever you did, but that shall never happen...'],...
                'warning');
    end
end

function keypress_Callback(~,evt)
    try
        if isempty(evt.Character) && isempty(evt.Key)
            % In case "Character" is the empty string, i.e. only modifier
            % key was pressed...
            return;
        end
        if ~isempty(evt.Modifier)
            if (strcmpi(evt.Modifier{1},'command')) || ...
                    (strcmpi(evt.Modifier{1},'control'))
                switch evt.Key
                    case 'w'
                        delete(hMainFigure);
                        varargout{1} = oldLabel;
                    otherwise
                        return;
                end
            end
        end
        switch evt.Key
            case 'escape'
                delete(hMainFigure);
                varargout{1} = oldLabel;
            otherwise
                return;
        end
    catch exception
        throw(exception);
    end
end

function info_pushbutton_Callback(~,~)
    trEPRgui_infowindow();
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Utility functions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

end
