function handle = guiDatasetPanel(parentHandle,position)
% GUIDATASETPANEL Add a panel for dataset control to a gui
%       Should only be called from within a GUI defining function.
%
%       Arguments: parent Handle and position vector.
%       TODO: Add guidata and appdata to list of arguments
%
%       Returns the handle of the added panel.

% (Leave a blank line following the help.)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Construct the components
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

defaultBackground = get(parentHandle,'Color');

handle = uipanel('Tag','data_panel',...
    'parent',parentHandle,...
    'Title','Dataset display',...
    'FontWeight','bold',...
    'BackgroundColor',defaultBackground,...
    'Visible','off',...
    'Units','pixels','Position',position);

% Create the "Dataset display" panel
panel_size = get(handle,'Position');
uicontrol('Tag','data_panel_description',...
    'Style','text',...
    'Parent',handle,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'HorizontalAlignment','Left',...
    'FontAngle','oblique',...
    'Position',[10 panel_size(4)-60 panel_size(3)-20 30],...
    'String',{'Choose the datasets to be displayed in the main axes (on the left)'}...
    );

handle_p1 = uipanel('Tag','data_panel_invisible_panel',...
    'Parent',handle,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[10 panel_size(4)-170 panel_size(3)-20 100],...
    'Title','Invisible datasets'...
    );
uicontrol('Tag','data_panel_invisible_listbox',...
    'Style','listbox',...
    'Parent',handle_p1,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[10 10 panel_size(3)-40 70],...
    'String',''...
    );

handle_p2 = uipanel('Tag','data_panel_visible_panel',...
    'Parent',handle,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[10 panel_size(4)-360 panel_size(3)-20 140],...
    'Title','Visible datasets'...
    );
uicontrol('Tag','data_panel_visible_listbox',...
    'Style','listbox',...
    'Parent',handle_p2,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[10 50 panel_size(3)-40 70],...
    'String','',...
    'Callback',{@visible_listbox_Callback}...
    );
uicontrol('Tag','data_panel_accumulate_pushbutton',...
    'Style','pushbutton',...
    'Parent',handle_p2,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[10 10 100 30],...
    'String','Accumulate...'...
    );
uicontrol('Tag','data_panel_previous_pushbutton',...
    'Style','pushbutton',...
    'Parent',handle_p2,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[panel_size(3)-110 10 40 30],...
    'FontWeight','bold',...
    'String','<<',...
    'Callback',{@previous_pushbutton_Callback}...
    );
uicontrol('Tag','data_panel_next_pushbutton',...
    'Style','pushbutton',...
    'Parent',handle_p2,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[panel_size(3)-70 10 40 30],...
    'FontWeight','bold',...
    'String','>>',...
    'Callback',{@next_pushbutton_Callback}...
    );

uicontrol('Tag','data_panel_show_pushbutton',...
    'Style','pushbutton',...
    'Parent',handle,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[10 panel_size(4)-210 60 30],...
    'String','Show',...
    'Enable','off',...
    'Callback', {@show_pushbutton_Callback}...
    );
uicontrol('Tag','data_panel_hide_pushbutton',...
    'Style','pushbutton',...
    'Parent',handle,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[panel_size(3)-70 panel_size(4)-210 60 30],...
    'String','Hide',...
    'Enable','off',...
    'Callback', {@hide_pushbutton_Callback}...
    );
uicontrol('Tag','show_hide_button_explanation',...
    'Style','text',...
    'Parent',handle,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'HorizontalAlignment','Center',...
    'FontAngle','oblique',...
    'Position',[75 panel_size(4)-220 panel_size(3)-150 30],...
    'String',{'selected dataset'}...
    );

handle_p3 = uipanel('Tag','data_panel_currentlyactive_panel',...
    'Parent',handle,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[10 panel_size(4)-460 panel_size(3)-20 90],...
    'Title','Currently active dataset'...
    );
uicontrol('Tag','data_panel_save_pushbutton',...
    'Style','pushbutton',...
    'Parent',handle_p3,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[10 40 floor((panel_size(3)-40)/3) 30],...
    'String','Save'...
    );
uicontrol('Tag','data_panel_saveas_pushbutton',...
    'Style','pushbutton',...
    'Parent',handle_p3,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[floor((panel_size(3)-40)/3)+10 40 floor((panel_size(3)-40)/3) 30],...
    'String','Save as'...
    );
uicontrol('Tag','data_panel_remove_pushbutton',...
    'Style','pushbutton',...
    'Parent',handle_p3,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[(floor((panel_size(3)-40)/3)*2)+10 40 floor((panel_size(3)-40)/3) 30],...
    'String','Remove',...
    'Callback', {@remove_pushbutton_Callback}......
    );
uicontrol('Tag','data_panel_linestyle_pushbutton',...
    'Style','pushbutton',...
    'Parent',handle_p3,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[10 10 floor((panel_size(3)-40)/3) 30],...
    'String','Line style'...
    );
uicontrol('Tag','data_panel_getinfo_pushbutton',...
    'Style','pushbutton',...
    'Parent',handle_p3,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[floor((panel_size(3)-40)/3)+10 10 floor((panel_size(3)-40)/3) 30],...
    'String','Get info'...
    );
uicontrol('Tag','data_panel_complete_pushbutton',...
    'Style','pushbutton',...
    'Parent',handle_p3,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[(floor((panel_size(3)-40)/3)*2)+10 10 floor((panel_size(3)-40)/3) 30],...
    'String','Complete'...
    );

handle_p4 = uipanel('Tag','data_panel_displaytype_panel',...
    'Parent',handle,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[10 panel_size(4)-520 panel_size(3)-20 50],...
    'Title','Display type'...
    );
uicontrol('Tag','data_panel_displaytype_popupmenu',...
    'Style','popupmenu',...
    'Parent',handle_p4,...
    'BackgroundColor',defaultBackground,...
    'Units','Pixels',...
    'Position',[10 10 panel_size(3)-40 20],...
    'String','2D plot|1D along x|1D along y',...
    'Callback', {@displaytype_popupmenu_Callback}...
    );

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Initialization tasks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Callbacks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function show_pushbutton_Callback(source,eventdata)
    % Get appdata of main window
    mainWindow = findobj('Tag','trepr_gui_mainwindow');
    ad = getappdata(mainWindow);

    % Get handles of main window
    gh = guihandles(mainWindow);
    
    % Get selected item of listbox
    selected = get(gh.data_panel_invisible_listbox,'Value');

    % Move to visible
    ad.control.spectra.visible = [...
        ad.control.spectra.visible ...
        ad.control.spectra.invisible(selected) ...
        ];
    
    % Make moved entry active one
    ad.control.spectra.active = ad.control.spectra.invisible(selected);
    
    % Delete in invisible
    ad.control.spectra.invisible(selected) = [];
    
    % Update appdata of main window
    setappdata(mainWindow,'control',ad.control);
    
    % Update both list boxes
    update_invisibleSpectra();
    update_visibleSpectra();    
    
    %Update main axis
    update_mainAxis();
end


function hide_pushbutton_Callback(source,eventdata)
    % Get appdata of main window
    mainWindow = findobj('Tag','trepr_gui_mainwindow');
    ad = getappdata(mainWindow);

    % Get handles of main window
    gh = guihandles(mainWindow);
    
    % Get selected item of listbox
    selected = get(gh.data_panel_visible_listbox,'Value');

    % Move to invisible
    ad.control.spectra.invisible = [...
        ad.control.spectra.invisible ...
        ad.control.spectra.visible(selected) ...
        ];
    
    % Delete in visible
    ad.control.spectra.visible(selected) = [];
    
    % Toggle active entry
    if (selected > length(ad.control.spectra.visible))
        if (selected == 1)
            ad.control.spectra.active = 0;
        else
            ad.control.spectra.active = ad.control.spectra.visible(end);
        end
    else
        ad.control.spectra.active = ad.control.spectra.visible(selected);
    end
    
    % Update appdata of main window
    setappdata(mainWindow,'control',ad.control);
    
    % Update both list boxes
    update_invisibleSpectra();
    update_visibleSpectra();
    
    %Update main axis
    update_mainAxis();
end


function remove_pushbutton_Callback(source,eventdata)
    % Get appdata of main window
    mainWindow = findobj('Tag','trepr_gui_mainwindow');
    ad = getappdata(mainWindow);

    % Get handles of main window
    gh = guihandles(mainWindow);
    
    % Get selected item of listbox
    selected = get(gh.data_panel_visible_listbox,'Value');

    % Remove from data and origdata
    ad.data(ad.control.spectra.visible(selected)) = [];
    ad.origdata(ad.control.spectra.visible(selected)) = [];
    
    % Delete in visible
    ad.control.spectra.visible(selected) = [];
    
    % Shift numbering in spectra.visible and spectra.invisible
    if (~isempty(ad.control.spectra.visible))
        indices = find(ad.control.spectra.visible>selected);
        ad.control.spectra.visible(indices) = ...
            ad.control.spectra.visible(indices)-1;
    end
    if (~isempty(ad.control.spectra.invisible))
        indices = find(ad.control.spectra.invisible>selected);
        ad.control.spectra.invisible(indices) = ...
            ad.control.spectra.invisible(indices)-1;
    end
    
    % Toggle active entry
    if (selected > length(ad.control.spectra.visible))
        if (selected == 1)
            ad.control.spectra.active = [];
        else
            ad.control.spectra.active = ad.control.spectra.visible(end);
        end
    else
        ad.control.spectra.active = ad.control.spectra.visible(selected);
    end
    
    % Update appdata of main window
    setappdata(mainWindow,'control',ad.control);
    setappdata(mainWindow,'data',ad.data);
    setappdata(mainWindow,'origdata',ad.origdata);
    
    % Update both list boxes
    update_invisibleSpectra();
    update_visibleSpectra();
    
    %Update main axis
    update_mainAxis();
end

function displaytype_popupmenu_Callback(source,eventdata)
    % Get appdata of main window
    mainWindow = findobj('Tag','trepr_gui_mainwindow');
    ad = getappdata(mainWindow);

    displayTypes = cellstr(get(source,'String'));
    displayType = displayTypes{get(source,'Value')};
    ad.control.axis.displayType = displayType;
    
    % Update appdata of main window
    setappdata(mainWindow,'control',ad.control);
    
    update_mainAxis();
end

function visible_listbox_Callback(source,eventdata)
    % Get appdata of main window
    mainWindow = findobj('Tag','trepr_gui_mainwindow');
    ad = getappdata(mainWindow);

    % Get handles of main window
    gh = guihandles(mainWindow);

    ad.control.spectra.active = ad.control.spectra.visible(...
        get(gh.data_panel_visible_listbox,'Value')...
        );
    
    % Update appdata of main window
    setappdata(mainWindow,'control',ad.control);
    
    % Update processing panel
    update_processingPanel();
    
    % Update slider panel
    update_sliderPanel();
    
    % Update visible spectra listboxes (in diverse panels!)
    update_visibleSpectra();

    %Update main axis
    update_mainAxis();
end

function previous_pushbutton_Callback(source,eventdata)
    % Get appdata of main window
    mainWindow = findobj('Tag','trepr_gui_mainwindow');
    ad = getappdata(mainWindow);

    % Get handles of main window
    gh = guihandles(mainWindow);
    
    % This shall never happen, as the element should not be active in this
    % case
    if (length(ad.control.spectra.visible) < 2)
        return;
    end
    
    if (ad.control.spectra.active == ad.control.spectra.visible(1))
        ad.control.spectra.active = ad.control.spectra.visible(end);
    else
        ad.control.spectra.active = ad.control.spectra.visible(...
            find(ad.control.spectra.visible==ad.control.spectra.active)-1);
    end
    
    % Update appdata of main window
    setappdata(mainWindow,'control',ad.control);
    
    % Update processing panel
    update_processingPanel();
    
    % Update slider panel
    update_sliderPanel();
    
    % Update visible spectra listboxes (in diverse panels!)
    update_visibleSpectra();

    %Update main axis
    update_mainAxis();
end

function next_pushbutton_Callback(source,eventdata)
    % Get appdata of main window
    mainWindow = findobj('Tag','trepr_gui_mainwindow');
    ad = getappdata(mainWindow);

    % Get handles of main window
    gh = guihandles(mainWindow);
    
    % This shall never happen, as the element should not be active in this
    % case
    if (length(ad.control.spectra.visible) < 2)
        return;
    end
    
	if(ad.control.spectra.active == ad.control.spectra.visible(end))
        ad.control.spectra.active = ad.control.spectra.visible(1);
    else
        ad.control.spectra.active = ad.control.spectra.visible(...
            find(ad.control.spectra.visible==ad.control.spectra.active)+1);
    end
    
    % Update appdata of main window
    setappdata(mainWindow,'control',ad.control);
    
    % Update processing panel
    update_processingPanel();
    
    % Update slider panel
    update_sliderPanel();
    
    % Update visible spectra listboxes (in diverse panels!)
    update_visibleSpectra();

    %Update main axis
    update_mainAxis();
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Utility functions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

end