function varargout = trEPRgui_helpwindow(varargin)
% TREPRGUI_HELPWINDOW Help window for the trEPR GUI.
%
% This window provides the user with "online" help included within the GUI.
% Besides that, it gives access to all the other sources of additional
% help, such as the Matlab Help Browser and the toolbox website.
%
% Usage:
%   trEPRgui_helpwindow
%   handle = trEPRgui_helpwindow
%   trEPRgui_helpwindow(<parameter>,<value>)
%
% Optional parameters that can be set:
%
%   page      - string
%               Page that should be displayed in the help window.
%               To discern pages with identical name in different
%               subdirectories, a slash ("/") can be used to separate
%               directory and file.
%
%               If the respective page cannot be found, a default page is
%               displayed.
%
% See also: helpWindow

% Copyright (c) 2011-14, Till Biskup
% 2014-08-10

% Parse input arguments using the inputParser functionality
try
    p = inputParser;            % Create inputParser instance.
    p.FunctionName = mfilename; % include function name in error messages
    p.KeepUnmatched = true;     % Enable errors on unmatched arguments
    p.StructExpand = true;      % Enable passing arguments in a structure
    p.addParamValue('page','',@(x)ischar(x));
    p.parse(varargin{:});
catch exception
    disp(['(EE) ' exception.message]);
    return;
end

% Get basedir
[basedir,~,~] = fileparts(mfilename('fullpath'));

hMainFigure = helpWindow(...
    'tag',mfilename,...
    'title','trEPR GUI',...
    'basedir',fullfile(basedir,'helptexts','main'),...
    'page',p.Results.page,...
    'visible',false ...
    );

% Add additional buttons
defaultBackground = get(hMainFigure,'Color');

uicontrol('Tag','help_panel_about_pushbutton',...
    'Style','pushbutton',...
    'Parent',hMainFigure,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[330 10 70 30],...
    'TooltipString','Show general info about the trEPR toolbox and GUI',...
    'String','About',...
    'KeyPressFcn',get(hMainFigure,'KeyPressFcn'),...
    'Callback',{@(~,~)trEPRgui_aboutwindow}...
    );
uicontrol('Tag','help_panel_website_pushbutton',...
    'Style','pushbutton',...
    'Parent',hMainFigure,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[400 10 70 30],...
    'TooltipString',sprintf('%s\n%s',...
    'Open website of the trEPR toolbox (in system webbrowser)',...
    '(Warning: Apparently that does not work with Windows.)'),...
    'String','Website',...
    'KeyPressFcn',get(hMainFigure,'KeyPressFcn'),...
    'Callback',{@(~,~)webbrowser(trEPRinfo('url'))}...
    );

set(hMainFigure,'Visible','on');

end
