function status = update_sliderPanel()
% UPDATE_SLIDERPANEL Helper function that updates the slider panel
%   of the trEPR GUI, namely trEPR_gui_mainwindow.
%
%   STATUS: return value for the exit status
%           -1: no tEPR_gui_mainwindow found
%            0: successfully updated main axis

% Is there currently a trEPRgui object?
mainWindow = findobj('Tag','trepr_gui_mainwindow');
if (isempty(mainWindow))
    status = -1;
    return;
end

% Get handles from main window
gh = guidata(mainWindow);

% Get appdata from main GUI
ad = getappdata(mainWindow);

switch ad.control.axis.displayType
    case '2D plot'
        return;
    case '1D along x' % time profile
        % Update slider panel
        set(...
            gh.slider_panel_position_x_index_edit,...
            'String',...
            ad.data{ad.control.spectra.active}.display.position.y...
            );
        [y,x] = size(ad.data{ad.control.spectra.active}.data);
        y = linspace(1,y,y);
        if (isfield(ad.data{ad.control.spectra.active},'axes') ...
                && isfield(ad.data{ad.control.spectra.active}.axes,'y') ...
                && isfield(ad.data{ad.control.spectra.active}.axes.y,'values') ...
                && not (isempty(ad.data{ad.control.spectra.active}.axes.y.values)))
            y = ad.data{ad.control.spectra.active}.axes.y.values;
        end
        set(...
            gh.slider_panel_position_x_unit_edit,...
            'String',...
            y(ad.data{ad.control.spectra.active}.display.position.y)...
            );
    case '1D along y' % B0 spectrum
        % Update slider panel
        set(...
            gh.slider_panel_position_y_index_edit,...
            'String',...
            ad.data{ad.control.spectra.active}.display.position.x...
            );
        [y,x] = size(ad.data{ad.control.spectra.active}.data);
        x = linspace(1,x,x);
        if (isfield(ad.data{ad.control.spectra.active},'axes') ...
                && isfield(ad.data{ad.control.spectra.active}.axes,'x') ...
                && isfield(ad.data{ad.control.spectra.active}.axes.x,'values') ...
                && not (isempty(ad.data{ad.control.spectra.active}.axes.x.values)))
            x = ad.data{ad.control.spectra.active}.axes.x.values;
        end
        set(...
            gh.slider_panel_position_y_unit_edit,...
            'String',...
            x(ad.data{ad.control.spectra.active}.display.position.x)...
            );
    otherwise
        msg = sprintf('Display type %s currently unsupported',ad.control.axis.displayType);
        add2status(msg);
end

status = 0;

end