function types = markerTypes
% MARKERTYPES Return cell array of line styles in both descriptive manner
% and as symbols
%
% Usage:
%   types = markerTypes
%
%   types - cell array
%           1st column: description of marker types
%           2nd column: symbols understood by Matlab(r) for marker types

% Copyright (c) 2014, Till Biskup
% 2014-08-07

types = {...
    'none','none'; ...
    'plus','+'; ...
    'circle','o'; ...
    'asterisk','*'; ...
    'point','.'; ...
    'cross','x'; ...
    'square','s'; ...
    'diamond','d'; ...
    'triangle up','^'; ...
    'triangle down','v'; ...
    'triangle right','<'; ...
    'triangle left','>'; ...
    'pentagram','p'; ...
    'hexagram','h'; ...
    'none','none' ...
    }; ...

end
